### ISSUE TITLE
IP-Adresse über Anruf herausfinden

### ISSUE THREAD

**Issue by YK18415** [YK18415/TeamAndroid#2]

**Comment by YK18415** [comment]
in order to send any pictures/data/messages/replies/whateverthefucks over the internet we require the ip-address of the receiver. if we cannot figure this out or if this turns out to be impossible to figure out, we will have to enter the ip address manually before sending the picture/reply. this is only a plan b and we shall try to find a way to prevent this.

**Comment by StephanToennies** [comment]
Problem:
- a phone call goes over the telecomunication network, not over voice-over-ip.

Consequences:
- IP adress can't be gotten by regular phone call
-  we have to write the ip adress manuely (this is not a good way)
